resource "aws_efs_file_system" "volume" {
	creation_token = "efs-vol-${var.prj_environment}-${var.prj_ecosystem}-${var.prj_application}"
	#reference_name = "EFS-Volume-${var.prj_environment}-${var.prj_ecosystem}-${var.prj_application}"
	performance_mode = "generalPurpose"
	tags {
		Name			= "EFS-Volume-${var.prj_environment}-${var.prj_ecosystem}-${var.prj_application}"
		Resource		= "Volume"
		ResourceGroup	= "EFS"
		Ecosystem		= "${var.prj_ecosystem}"
		Application		= "${var.prj_application}"
		Environment		= "${var.prj_environment}"
	}
}

/*
AWS_EFS_FILE_SYSTEM
Provides an Elastic File System (EFS) resource.

resource "aws_efs_file_system" "foo" {

	creation_token
	#(Optional) A unique name (a maximum of 64 characters are allowed) used as reference when creating the the Elastic File System to ensure idempotent file system creation. By default generated by Terraform. See Elastic File System user guide for more information.
	
	reference_name
	#DEPRECATED (Optional) A reference name used when creating the Creation Token which Amazon EFS uses to ensure idempotent file system creation. By default generated by Terraform.
	
	performance_mode
	#(Optional) The file system performance mode. Can be either "generalPurpose" or "maxIO" (Default: "generalPurpose").
	
	tags ()
	#(Optional) A mapping of tags to assign to the file system.
}


Attributes Reference
The following attributes are exported:

	id - The ID that identifies the file system (e.g. fs-ccfc0d65).
	
*/